tracer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app01/', include('app01.urls', namespace='app01')),
    url(r'^', include('web.urls')),
]

web/urls.py
from django.conf.urls import url
from django.contrib import admin
from web.view import account

from app01 import views

urlpatterns = [
    url(r'^register/$', account.register, name='register'),  # register
    url(r'^send/sms/$', account.send_sms, name='send_sms'),
]

web/models.py
from django.db import models


# Create your models here.


class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32)
    email = models.EmailField(verbose_name='邮箱', max_length=32)
    mobile_phone = models.CharField(verbose_name='手机号', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)

web/templates/register.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 用户注册 {% endblock %}


{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="account">
        <div class="title">用户注册</div>
        <form id="form" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-xs-7">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-xs-5">
                                <input id="btnSms" type="button" class="btn btn-default" value="点击获取验证码">
                            </div>
                        </div>

                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>

                {% endif %}
            {% endfor %}

            <div class="row">
                <div class="col-xs-3">
                    <input type="button" class="btn btn-primary" value="注  册"/>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
        // 页面框架加载完成之后自动执行函数
        $(function () {

            bindClickBtnSms();
        });

        /*
        点击获取验证码的按钮绑定事件
         */
        function bindClickBtnSms() {
            $('#btnSms').click(function () {

                $('.error-msg').empty();

                // 获取用户输入的手机号
                // 找到输入框的ID，根据ID获取值，如何找到手机号的那个ID？
                var mobilePhone = $('#id_mobile_phone').val();

                // 发送ajax请求，把手机号发送过去
                $.ajax({
                    url: "{% url 'send_sms' %}", // 等价于 /send/sms/
                    type: "GET",
                    data: {mobile_phone: mobilePhone, tpl: "register"},
                    dataType: "JSON", // 将服务端返回的数据反序列化为字典
                    success: function (res) {
                        // ajax请求发送成功之后，自动执行的函数； res就是后端返回的值
                        if (res.status) {
                            {#console.log('发送成功，倒计时')#}
                            sendSmsRemind();
                        } else {
                            // 错误信息
                            // console.log(res); // {status:False, error:{ mobile_phone: ["错误信息"，],code: ["错误信息"，] }  }
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })

            })
        }

        /*
        倒计时
         */
        function sendSmsRemind() {
            var $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true); // 禁用
            var time = 60;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000)

        }

    </script>
{% endblock %}